<?php 
    // this file was generated by gulpfile.js 
    print( '
<link rel="preload" href="' . $assetsPath . 'fonts/merriweather-v30-latin_latin-ext-regular.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="' . $assetsPath . 'fonts/merriweather-v30-latin_latin-ext-italic.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="' . $assetsPath . 'fonts/merriweather-v30-latin_latin-ext-700.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="' . $assetsPath . 'fonts/fa-solid-900.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="' . $assetsPath . 'fonts/fa-brands-400.woff2" as="font" type="font/woff2" crossorigin>
' );