<?php 
    // this file was generated by gulpfile.js 
    print( '
<link rel="preload" href="' . $assetsPath . 'fonts/Roboto-Regular.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="' . $assetsPath . 'fonts/Roboto-Light.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="' . $assetsPath . 'fonts/Roboto-Medium.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="' . $assetsPath . 'fonts/fa-solid-900.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="' . $assetsPath . 'fonts/fa-brands-400.woff2" as="font" type="font/woff2" crossorigin>
' );